### ISSUE TITLE
The requested Payment Method is not available

### ISSUE THREAD

**Issue by gaiterjones** [therouv/Magento-DebitPayment#66]
I have upgraded a Magento 1.3 database to 1.9.1. The 1.3 shop used the Mage_Debit module v1.0.0. For the 1.9 shop I installed the new itabs_debit module via Magento connect. Everything seems to work fine, the payment method is configured correctly however when I try and save customer data I get an exception error 'The requested Payment Method is not available'. I suspect the exception is coming from the debit module but I do not know why. Do you have any suggestions? One exception report I am seeing from the front end looks like this

a:5:{i:0;s:49:"The requested Payment Method is not available. []";i:1;s:2621:"#0 /home/www/magento/app/code/core/Mage/Payment/Model/Info.php(83): Mage::throwException('The requested P...')
#1 /home/www/magento/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
#2 /home/www/magento/app/code/community/Itabs/Debit/Model/Observer.php(170): Mage_Sales_Model_Quote_Payment->getMethodInstance()
#3 /home/www/magento/app/code/community/Itabs/Debit/Model/Observer.php(125): Itabs_Debit_Model_Observer->_encryptPaymentData(Object(Mage_Sales_Model_Quote_Payment))
#4 /home/www/magento/app/code/core/Mage/Core/Model/App.php(1338): Itabs_Debit_Model_Observer->encryptBankDataInAdminhtmlQuote(Object(Varien_Event_Observer))
#5 /home/www/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Itabs_Debit_Model_Observer), 'encryptBankData...', Object(Varien_Event_Observer))

Any assistance would be appreciated.

**Comment by gaiterjones** [comment]
Just an update on this problem, the exception is being thrown in 

public function encryptBankDataInAdminhtmlQuote(Varien_Event_Observer $observer)

The error is not seen with all customers, seems to affect older customer accounts. If I change Mage::register('debit_payment_quote_data_processed', true, true); so that the payment data has already been processed returns true, and not false, there is no error. If you can assist with further debugging I would appreciate it.

**Comment by thomasklosinsky** [comment]
Exactly same problem. And your fix solved my problem too, but that's bad hack, I think... any other ideas from therouv yet?

**Comment by gaiterjones** [comment]
yes it is a bad hack, but its been running in a live shop for a few weeks now without any affect on orders with this payment method. It is a shame that the developers have not commented on this.

**Comment by carofi** [comment]
The lines above are already in the file. but it doesn't work.
(it's in file /app/code/community/Itabs/Debit/Model/Observer.php correct?)

The problem seems to be the following... we used "Lastschrift" over years. Then changed to SEPA - and now old customers with previous orders via "Lastschrift" cannot be opened. Orders are ok and visible but when you try to access the customer there ist the above mentioned error.

**Comment by gaiterjones** [comment]
Yes the change is in Observer.php. Did you upgrade Itab_Debit in order to get the new SEPA functionality? I seem to remember a problem I had after upgrading a very old version of the module  where the new version setup had not ran properly and this also caused problems opening orders.
